// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaJtKF87E37e2Gg0BMCXkeA_dp4vS4pmM',
    appId: '1:839225215983:web:2026d821d79c4899c7041a',
    messagingSenderId: '839225215983',
    projectId: 'hometutorapp-e9529',
    authDomain: 'hometutorapp-e9529.firebaseapp.com',
    storageBucket: 'hometutorapp-e9529.appspot.com',
    measurementId: 'G-TR0TCY5QKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbWDy0GTTYSQbWUFS1VLAzNVytgX3ZD14',
    appId: '1:839225215983:android:6dae3eaf22af92e1c7041a',
    messagingSenderId: '839225215983',
    projectId: 'hometutorapp-e9529',
    storageBucket: 'hometutorapp-e9529.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAroa_uuFqIR6cxf3V99UEEtuuS5bljIyk',
    appId: '1:839225215983:ios:a2c30b469f707fb2c7041a',
    messagingSenderId: '839225215983',
    projectId: 'hometutorapp-e9529',
    storageBucket: 'hometutorapp-e9529.appspot.com',
    iosClientId: '839225215983-6kpqt02rrsj9ovvte9jffn4bfkehsr4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.testproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAroa_uuFqIR6cxf3V99UEEtuuS5bljIyk',
    appId: '1:839225215983:ios:a2c30b469f707fb2c7041a',
    messagingSenderId: '839225215983',
    projectId: 'hometutorapp-e9529',
    storageBucket: 'hometutorapp-e9529.appspot.com',
    iosClientId: '839225215983-6kpqt02rrsj9ovvte9jffn4bfkehsr4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.testproject',
  );
}
